[workspace]
members = ["delivery-service", "core", "pumpe", "tugboat"]
resolver = "2"

[workspace.dependencies]
axum = "0.7.7"
serde = "1.0.217"
thiserror = "2.0.9"
tls_codec = "0.4.1"
tokio = "1.48.0"
tower-http = "0.6.1"
